services:
  - type: web
    name: worldotutor-chat
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
